version: "3"
services:
  nginx:
    build:
      context: nginx
    ports:
      - "8001:80"

  backend:
    build:
      context: src
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file: .env

  tests:
    build:
      context: tests/functional
    entrypoint: >
      sh -c "
        python wait_for_es.py &&
        python wait_for_redis.py &&
        pytest src
      "
    depends_on:
      backend:
        condition: service_started
    env_file: .env

  elastic:
    build:
      context: data/elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  redis:
    image: redis:7.2.0
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - rd_data:/data

networks:
  default:
      name: movies-tests

volumes:
  rd_data:
  es_data: