version: "3.8"

services:
  elastic:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
    ports:
      - "9200:9200"
    volumes:
      - es_data_test:/usr/share/elasticsearch/data

  redis:
    image: redis:alpine
    volumes:
      - rd_data_test:/data
    ports:
      - "6379:6379"

  backend:
    build: ./src
    env_file:
      - ./.env
    ports:
      - "8000:8000"

volumes:
  rd_data_test:
  es_data_test:
