line-length = 120
exclude = ["testdata"]

[lint]
select = [
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "E",  # pycodestyle
    "ERA",  # eradicate
    "F",  # pyflakes
    "I",  # isort
    "N",  # pep8-naming
    "Q",  # flake8-quotes
    "T10",  # flake8-debugger
    "W",  # pycodestyle
]
ignore = ["B904", "B012"]